apiVersion: v1
kind: Secret
metadata:
  name: empmgmt-postgresql
  namespace: jhipster
  labels:
    app: empmgmt-postgresql
type: Opaque
data:
  postgresql-password: MGIxYjJkNDk0OTFjYjJkN2ZiYjk3Y2RhYjU0OGFjNDVlMGM2NDQ3ZDEwMTliYjkzOTZkYmE1NTdmMTBm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empmgmt-postgresql
  namespace: jhipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empmgmt-postgresql
  template:
    metadata:
      labels:
        app: empmgmt-postgresql
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.1
          env:
            - name: POSTGRES_USER
              value: empmgmt
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: empmgmt-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: empmgmt-postgresql
  namespace: jhipster
spec:
  selector:
    app: empmgmt-postgresql
  ports:
    - port: 5432
